/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaapplication1;

import javax.swing.table.*;

/**
 *
 * @author Wizard
 */
public class RoutineForm extends javax.swing.JDialog 
{

    /**
     * Creates new form RoutineForm
     */
    public RoutineForm() 
    {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setModal(true);  
    }

    public void SetDate(int year, int month, int day)
           throws java.sql.SQLException, ClassNotFoundException
    {
        if(Year == year && Month == month && Day == day)
            return;
        Year = year;
        Month = month;
        Day = day;
        this.setTitle("日程安排 " + String.valueOf(year) + "年" +
                      String.valueOf(month) + "月" + String.valueOf(day) + "日");
        Routine.Load(year, month, day);
        Routine.Show(RoutineTable);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        RoutineTable = new javax.swing.JTable();

        RoutineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "事件名称", "起始时间", "截止时间", "提醒方式", "提醒时间", "备注"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(RoutineTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RoutineTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private int Year;
    private int Month;
    private int Day;
    private RoutineManager Routine
            = new RoutineManager();
}